import type { AnalysisResult } from "./types";

/** One downsampled peak, placed on the shared time axis. */
export interface WaveformBar {
  x: number;
  halfHeight: number;
}

/** One onset, placed on the shared time axis, for reading against the beat gridlines. */
export interface OnsetMark {
  x: number;
}

/**
 * One Track's row: its own vertical band of the canvas, plus its peaks and
 * onsets placed on the time axis shared by every row (issue #20). Onsets are
 * kept separate from the peak bars because it's the onset-vs-gridline
 * position, not the waveform shape, that shows a Track is ahead or behind.
 */
export interface WaveformRowLayout {
  trackId: string;
  label: string;
  centerY: number;
  rowHeight: number;
  bars: WaveformBar[];
  onsets: OnsetMark[];
}

/**
 * Pixel geometry for the stacked waveform canvas (ADR 0004), computed from
 * the same `AnalysisResult` the report is written from so the canvas and the
 * file can never disagree. Kept framework-free and pure so it's testable the
 * same way as `downsamplePeaks`/`analyseTrack` — the React component that
 * draws it is a thin, untested wrapper.
 */
export interface WaveformCanvasLayout {
  width: number;
  height: number;
  durationMs: number;
  rows: WaveformRowLayout[];
  /** x positions of the beat grid, shared across every row's time axis. */
  gridlineXs: number[];
}

const ROW_VERTICAL_PADDING = 4;

export function computeWaveformCanvasLayout(
  analysis: AnalysisResult,
  width: number,
  height: number
): WaveformCanvasLayout {
  const tracks = analysis.tracks;

  if (tracks.length === 0 || width <= 0 || height <= 0) {
    return { width, height, durationMs: 0, rows: [], gridlineXs: [] };
  }

  const durationMs = Math.max(
    ...tracks.map((t) => t.durationMs),
    ...tracks.flatMap((t) => t.expectedBeatTimesMs),
    1
  );
  const timeToX = (ms: number) => (ms / durationMs) * width;

  const rowHeight = height / tracks.length;
  const rowHalfHeight = Math.max(0, rowHeight / 2 - ROW_VERTICAL_PADDING);

  const rows: WaveformRowLayout[] = tracks.map((track, rowIndex) => {
    const centerY = rowIndex * rowHeight + rowHeight / 2;
    const bucketCount = track.peaks.length;

    const bars: WaveformBar[] = track.peaks.map((peak, bucketIndex) => {
      const bucketTimeMs = bucketCount > 0 ? (bucketIndex / bucketCount) * track.durationMs : 0;
      return { x: timeToX(bucketTimeMs), halfHeight: peak * rowHalfHeight };
    });

    const onsets: OnsetMark[] = track.detectedOnsetsMs.map((onsetMs) => ({
      x: timeToX(onsetMs),
    }));

    return { trackId: track.trackId, label: track.label, centerY, rowHeight, bars, onsets };
  });

  // Every Track's expected grid is generated by the same function against
  // the same params (ADR 0004), so any one Track's grid represents them all.
  const gridlineXs = tracks[0].expectedBeatTimesMs.map(timeToX);

  return { width, height, durationMs, rows, gridlineXs };
}
